app:
  port: 7002
  name: rlease
  logPath: logs/rlease
  tickDuration: 5
  rolloutFaildCount: 10 #最大发布失败重试次数
  limit:
    maxConnects: 200
    maxQPS: 100

db:
  pgsqlsdn: "host=172.25.0.1 user=postgres password=123456 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"

casbin:
  #默认为true启用，false禁用时所有请求都放行
  enable: true
  modelFile: rbac_model.conf
  debug: false
  # 是否启用定期自动加载规则策略
  autoLoad: false
  # 定期自动加规则载策略时间间隔（秒）
  autoLoadDuration: 60

gorm:
  # 是否开启调试模式
  debug: true
  # 设置连接可以重用的最长时间(单位：秒)
  maxLifetime: 7200
  # 设置数据库的最大打开连接数
  maxOpenConns: 150
  # 设置空闲连接池中的最大连接数
  maxIdleConns: 50
  # 数据库表名前缀
  tablePrefix: "x_"
  # 是否启用自动映射数据库表结构,删除的字段不会删除，新数据写入时，删除的字段为null
  enableAutoMigrate: true


# otel:
#   endpoint: 127.0.0.1:4317